version: '3.7'

x-fp-activity-docker: &fp-activity
  build:
    context: .
    dockerfile: ./compose/Dockerfile
  image: whenessel/fp-activity:latest
  env_file:
    - ./docker-compose.env


services:

  eve:
    <<: *fp-activity
    container_name: fp-activity-eve
    restart: always
    command: runbot
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: activity-postgres
    restart: always
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432
    env_file:
      - ./docker-compose.env