# Generated by Django 4.1.6 on 2023-04-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('role_id', models.BigIntegerField(null=True)),
                ('channel_id', models.BigIntegerField(null=True)),
                ('message_id', models.BigIntegerField(null=True)),
                ('member_id', models.BigIntegerField()),
                ('member_name', models.CharField(blank=True, default='', max_length=255)),
                ('member_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'подготовка'), ('STARTED', 'запущено'), ('FINISHED', 'завершено'), ('CANCELED', 'остановлено')], default='PENDING', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('role_id', models.BigIntegerField(null=True)),
                ('channel_id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('role_id', models.BigIntegerField(null=True)),
                ('channel_id', models.BigIntegerField(null=True)),
                ('member_id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.BigIntegerField()),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('member_display_name', models.CharField(blank=True, max_length=255)),
                ('server', models.CharField(choices=[('Server 1', 'Сервер 1'), ('Server 2', 'Сервер 2'), ('Server 3', 'Сервер 3'), ('Server 4', 'Сервер 4'), ('Server 5', 'Сервер 5'), ('Server 6', 'Сервер 6')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='activity.event')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'member_id'), name='event-attendance-member'),
        ),
    ]
